anime-list-master.xml

Added the tvdbid for this anime. It's called "From Today On, It's My Turn!!" there.

Added tvdbid for Kyou kara Ore wa!!

---

anime-list-master.xml

The tvdbid currently there points to Future Card Buddyfight.

Fix tvdbid for Gakusen Toshi Asterisk (2016)

---

anime-list-master.xml

Added some titles that were missing and 1 correction. I did not run the bat file. 
Thx for your hard work on maintaining the list.

Added some titles

---

anime-list-master.xml

Added or corrected data for some entries to the best of my abilities
The entry I'm not fully sure of is the Kyou no go no ni (anidb:4241) where "S4 Kagaijugyou: Mizukake" is probably not 100% correctly mapped.
But at least Gekijouban Sidonia no Kishi won't map to fate stay night unlimited blade works.
I haven't run the .bat files.

Added some series and corrected some entries

---

anime-list-full.xml
anime-list-master.xml
anime-list-todo.xml
anime-list.xml

Add Urara Meirochou Mapping.

---

anime-movieset-list.xml

generate-lists.bat has been run.

Update Studio Ghibli Collection.

---

README.md
generate-lists.sh

I'm new to github and this is my first request.
I've added generate-lists.sh and documented it in README.md for Linux and other POSIX system users.

Add shell script to generate the xml files.

---

anime-list-full.xml
anime-list-master.xml
anime-list.xml

Eureka Seven special fix

---

anime-list-full.xml
anime-list-master.xml
anime-list-todo.xml
anime-list.xml

This series is a set of specials under 'Eureka Seven'.

Add tvdbid for 'Aratanari Fukaki Ao'

---

anime-list-full.xml
anime-list-master.xml
anime-list.xml

The OAD is tvdb special 1 and the season one recap special is special 2.

Fix specials mapping for Kekkai Sensen

---

anime-list-full.xml
anime-list-master.xml
anime-list.xml

- Unlimited Blade Works (2014) - episode 1 on AniDB is the Prologue located in the specials of theTVDB
- Boruto - The offset was wrong compared to theTVDB

Fix for Unlimited Blade Works (2014) and Boruto

---

anime-list-full.xml
anime-list-master.xml
anime-list.xml

Berserk movies - tvdbid fix
Appleseed XII movies - offset fix
Psycho-Pass Movie - offset fix
Mapping list fixes for:
- Fullmetal Panic Fumoffu/Second Raid
- Sailor Moon movies
- Kuroshitsuji
- Angel Beats
- Durarara / x2
- Kill la Kill
- Dimension W

Lots o' fixes

---

anime-list-full.xml
anime-list-master.xml
anime-list.xml

Fixed the mapping-list for Kekkai Sensen

Fix Kekkai Sensen specials

---

anime-list-full.xml
anime-list-master.xml
anime-list.xml

Full Metal Panic TSR - Fixed mapping list season
JoJo - Fixed tvdb season and movie special

More fixes

---

anime-list-full.xml
anime-list-master.xml
anime-list-todo.xml
anime-list.xml

- Updated all the Fate/Grand Order series to have a `tvdbid`

Fate Grand Order updates

---

anime-list-full.xml
anime-list-master.xml
anime-list-todo.xml
anime-list.xml

Added mappings for;
- Nekopara
- Pingu in the City

Additional mappings

---

anime-list-full.xml
anime-list-master.xml
anime-list-todo.xml
anime-list.xml

Fix specials mapping of season 1 (a8660), and season 2 (a9409).  Add
tvdbid and season for season 4 (a12498) (yet to be aired, but in tvdb).

Fixes or High School Dxd's

---

anime-list-full.xml
anime-list-master.xml
anime-list-todo.xml
anime-list.xml

dunno if this thing works it's my first pull

Added tvdb for Go-Toubun no Hanayome (anidb-14247)

---

anime-list-master.xml

Some of these are taken from other language versions than English of TheTVDB.

Noir: null-map special missing in TVDB, map existing ones

---

anime-list-master.xml

Null-mapping specials that would fallback into conflicting with movies that occupy the special episode slots.

Shinseiki Evangelion: specials fixes

---

anime-list-master.xml

Null-map specials from both aid 23 and 219 that would conflict with specials from aid 219 that are actually present on TheTVDB.

Cowboy Bebop: specials fixes

---

anime-list-master.xml

Null-map conflicting specials from aid 27 and 5426 that would conflict with fallbacks from aid 206, 2533, 4153 and 7973. Clean up unnecessary mapping-list for 7973.

Aa! Megami-sama!: specials fixes

---

anime-list-master.xml

Null-map overlapping specials.

Ai Yori Aoshi: specials fixes

---

anime-list-master.xml

TheTVDB is doing some weird stuff with this anime. This attempts to shuffle stuff back in place.

Hoshi no Koe: mapping fixes

---

anime-list-master.xml

Shuffle specials back into their proper spot.

Azumanga Daiou: specials fixes

---

anime-list-master.xml

Shifts specials into position that were shuffled around on TheTVDB. Null-map conflicts.

Mahoromatic: speceials fixes

---

anime-list-master.xml

Seems some nasty shuffling went down on TheTVDB. This puts the maps back in place where they should be.

Gundam Wing: reorder mappings and fix specials

---

anime-list-master.xml

Null-map special because the spin-off OVA lives there.

Kite: back on TheTVDB. New ID.

---

anime-list-master.xml

Specials from main show were misplaced.

Kanojo to Kanojo no Neko: fix mapping

---

anime-list-master.xml

Kind of chaotic out of order episodes here.

Princess Tutu: specials mapping conflicts

---

anime-list-master.xml

Bunch of shuffling around specials to match what's on TheTVDB.

Di Gi Charat: fix specials

---

anime-list-master.xml

Reshuffling seems to have happened on TheTVDB. This puts these back in place.

Da Capo: fix some specials

---

anime-list-master.xml

Correct all maps since TheTVDB mostly lists the Naisho specials, while AniDB has a whole bunch of other things going on.

Maria-sama ga Miteru: specials fixes

---

anime-list-master.xml

A lot of overlapping maps that needed to be adjusted.

Appleseed: fix specials

---

anime-list-master.xml

also a missing semicolon I saw

Higurashi no Naku Koro ni: special conflict solving

---

README.md
anime-list-full.xml
anime-list-master.xml
anime-list-todo.xml
anime-list-unknown.xml
anime-list.xml
update.bat
update.sh

I went through all the open issues again, as well as the remaining pull-request, to make sure everything was addressed, and, aside from issue #251, which has multiple potential solutions, this should fix everything that hadn't been fixed, as well as update fixes that needed updating. 
Also includes various other additional mappings.

Changes from issues, etc.

---

anime-list-master.xml

TVDB for some reason lists Puni Puni Poemi as part of Excel Saga, which it... kinda is, but there's also a TVDB ID for Puni Puni Poemi.

misc fixes

---

anime-list-full.xml
anime-list-master.xml
anime-list-todo.xml
anime-list.xml

Fixed the issues that popped up before.

Additional Series Updates

---

anime-list-full.xml
anime-list-master.xml
anime-list-todo.xml
anime-list.xml
anime-movieset-list.xml

Saiyuki was re-worked and corrected on TVDB after someone semi-vandalized/went crazy with it.

Multiple Updates

---

anime-list-full.xml
anime-list-master.xml
anime-list-todo.xml
anime-list.xml
anime-movieset-list.xml

Additional series added for Summer and Fall 2020. Should close tickets ScudLee#319, ScudLee#320, ScudLee#321, ScudLee#322, ScudLee#325, ScudLee#326, ScudLee#330, ScudLee#331.

Summer 2020, Fall 2020, and closing open tickets

---

anime-list-full.xml
anime-list-master.xml
anime-list-todo.xml
anime-list.xml

Close issues #333, #329, #324.
@slohj, @ScudLee -- a lot of the open tickets, in general, can be closed. They've mostly been accounted for by my past few commits. I can't close them.

Close open issues
