ScudLee/anime-lists

anime-list-master.xml

The current tvdbid that's filled in for Ookami Shoujo seems to be an invalid one, no tv series exists with that id. I've changed it to the correct one now.
For Little Witch Academia the episode mapping was incorrect, I fixed it so it maps to episode 3x03 now. I hope I mapped it correctly. 
For The Enchanted Parade I added the same tvdbid as Little Witch Academia, where it seems to be considered a special. It's episode 1 of the specials so no episode mapping seemed necessary.

Fixes for Ookami Shoujo and Little Witch Academia 1 and 2

---

anime-list-master.xml

The tvdbid currently there points to B-Project: Kodou*Ambitious.
Thanks!

Fix tvdbid for Danganronpa 3: Mirai Hen

---

anime-list-full.xml
anime-list-master.xml
anime-list.xml

- One Piece Film: Gold - Fixed the offset and special mapping
- One Piece Film: Z - Changed the main to use the `episodeoffset`, added a missing special
- The Last: Naruto The Movie - Fixed the offset
- Evangelion movies - Updated to use `episodeoffset` (seems cleaner than using the mapping-list, this can be removed if anyone disagrees)

Various fixes

---

anime-list-master.xml

Null-map specials from aid 18 so that the ones from 71, 8732 and 8733 can slot in where they belong. Also cleans away unnecessary mapping-lists when episodeoffset is available.

Musekinin Kanchou Tylor: specials fixes

---

anime-list-master.xml

Null-map conflicting special from aid 30 that would conflict through fallback with later aids 429, 2894 and 8976. Map in aid 2894 that was previously a music video, but exists as a special on TheTVDB. Shift back into place wrongly mapped specials.

X: specials fixes

---

anime-list-master.xml

Null-map specials from aid 35 that would conflict with later aids 49, 51 and 52. Properly map Love Live Hina to s0e4 and Final Selection to s0e3. Remove unnecessary mapping-entry for Love Hina Again.

Love Hina: specials fixes

---

anime-list-master.xml

Null-map a special from aid 39 and 95 that each would fallback map into conflicts with later aid.

Slayers: specials fixes

---

anime-list-master.xml

Null-mapping specials from aid 47 that conflict with its later OVAs in aid 8342. Also null-mapping specials from aid 8342 that would fallback map unto itself.

s.CRY.ed: specials fixes

---

anime-list-master.xml

Null-map conflicting special episode 2 now that TheTVDB is aware of Hand Maid Mai. Map in Hand Maid Mai as s0e2. Null-map its special that would map unto itself through fallback.

Hand Maid May: specials fixes

---

anime-list-master.xml

Lots of null-mapping of excess specials that would conflict with later mappings. Shift Tachikoma episodes back into place after TheTVDB did some reordering. Remove unnecessary mapping-list entries.

Ghost in the Shell: specials fixes and etc

---

anime-list-master.xml

Null-map specials from aid 73, 90 and 8595. Clean up some unnecessary mapping entries.

Rurouni Kenshin: specials fixes

---

anime-list-master.xml

Null-map some specials that are mapped elsewhere

SDF Macross: specials fixes

---

anime-list-master.xml

TheTVDB has removed the entirety of what they had defined as season 3 and put it as specials. This fixes the mappings back in order.

Fushigi Yuugi: specials and mapping fixes

---

anime-list-master.xml

With the release of Clear Card Hen, a bunch of shuffling happened on TheTVDB. This shuffles stuff back in places and maps previously unmapped episodes.

Card Captor Sakura: mapping fixes

---

anime-list-master.xml

For some reason Blood: The Last Vampire is an episode for Blood+ on TheTVDB, but it has a special that would map unto itself. Blood+ also has a special that would map onto that again. Null-mapping it.

Blood: specials fixes

---

anime-list-master.xml

Some shuffling happened on TheTVDB. aid 2700 is now s0e1 and s0e2. We're mapping special #1 for aid 113 to s0e3 where it now has been shuffled to.

Seishuuheiki Kanojo: specials mapping

---

anime-list-master.xml

OVA at aid 424 was shuffled to the front and omakes are now on TheTVDB. This maps this change.

Magic Knight Rayearth: specials fixes

---

anime-list-master.xml

Null-maps 15 specials from aid 137 and one from aid 169. Meshimase at aid 10518 covers most of season 0 on TheTVDB.
I've nullmapped so that nothing occupies s0e1 because Legend of Crystania at 1478 belongs to two TheTVDB IDs; 78777 and 85312. We're mapping the latter right now, but who knows if that could change...

Lodoss: fix specials mapping and add in Meshimase Lodoss

---

anime-list-master.xml

They were overlapping with actual episodes.

Macross 7: null-map some specials

---

anime-list-master.xml

These have been done after reviewing old DVDs and content from that time period. AniDB lists an originally separated set of episodes while TheTVDB is using the new release where they appeared as one singular track.

Full Metal Alchemist: fix specials

---

update.bat
update.sh

Anidb recently changed policy on the animetitles.xml access and requires
that the requesting project is announced in the useragent string.

Add useragent string to curl

---

anime-list-master.xml

Sword Oratoria (a11974) was mapped to the empty Season 0 of its own TVDB entry. Fixed.
Noir (a13) mapping no longer accurate, as TVDB specials were purged. Fixed.
Strike the Blood III (a13901) mapped.
Formatting changes related to use of offsets vs. mapping lists.

Fixes for a11974 and a13, mapping for a13901, minor formatting

---

anime-list-full.xml
anime-list-master.xml
anime-list-todo.xml
anime-list-unknown.xml
anime-list.xml

This should largely finish up the mappings for the Fall 2019 season.
Note that I am pretty much basing this off of the [AniDB Season Chart](https://anidb.net/anime/season/?do.filter=1) as it was on **2019/10/03**. 
I did a quick comparison between the **animetitles.xml** from then and the one currently used by the anime-lists, and included the newest series added at the end, but I know there are at least a handful of entries on AniDB that were not yet included in the latest **animetitles.xml** on GH (One 18+ OVA, and an unknown number of regular entries).
PS: See commit comment for list of entries mapped, alongside their AniDB-ID.

Additions - Fall 2019
